<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>
   


   
    <form action="" method="POST">
        <input type="text" placeholder="email" name="email">
        <input type="password" placeholder="password" name="password">
        <?php if (isset($error_message)) : ?>
            <p><?= $error_message; ?></p>
        <?php endif; ?>
        <input type="submit" value="submit">
    </form>







</body>

</html>