<div class="background"></div>
<div class="administration_container">
    <div class="administration_list">
        <div id="users" class="users clickStyle">
            <a class="a" href="#users_details"> <i class="fa-solid fa-users"></i>
                <p>Utilisateurs</p>
            </a>
        </div>
        <div class="announcements" id="announcements">
            <a href="#delivery_announcements_details" class="a"><i class="fa-solid fa-box-open"></i>
                <p>Annonces de livraison</p>
            </a>
        </div>
        <div class="requests" id="requests">
            <a href="#requests_details" class="a">
                <i class="fa-solid fa-hand"></i>
                <p>Demandes de livraison</p>
            </a>
        </div>
    </div>
    <div class="datas">

        <!-- ////////////////////////////////////////////////
         1ère div  
        ////////////////////////////////////// -->

        <div class="users_details an" id="users_details">
            <h4>Gestion des utilisateurs</h4>
            <div class="thead">
                <div class="name">Nom</div>
                <div class="role">Role</div>
                <div class="email">E-mail</div>
                <div class="phone">Téléphone</div>
                <div class="action">Action</div>

            </div>

            <?php
            foreach ($users as $user) { ?>

                <div class="user_infos">
                    <div class="name">
                        <div class="circle_icon user_connected user_circle_icon">
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <?= ucfirst($user->getFirstname()) . ' ' . ucfirst($user->getLastname()); ?>
                    </div>
                    <div class="role"> <span class=" <?php if ($user->getRole() == "admin") {
                                                            echo "adminDiv";
                                                        } else {
                                                            echo "noAdminDiv";
                                                        } ?>"><?= $user->getRole(); ?></span></div>
                    <div class="email"><?= $user->getEmail(); ?></div>
                    <div class="phone"><?= $user->getPhone_number(); ?></div>

                    <div class="action">

                        <button type="button" class="delete" name="delete" data_idUser="<?= $user->getIdUser(); ?>">
                            <i class="fa-solid fa-trash-can" title="Supprimer"></i>
                        </button>

                    </div>
                </div>


            <?php } ?>
            <div class="delete_user_popup" id="popup">
                <p>Voulez-vous vraiment supprimer cet utilisateur?</p>
                <form action="administration" method="post" id="delete_user_form">
                    <input type="hidden" name="id_user" id="id_user" value=''>
                    <div class="buttons">
                        <button type="submit" class='cancel_delete' name="cancel_delete">Annuler</button>
                        <button type="submit" class='button_delete' name="user_delete">Supprimer</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- ////////////////////////////////////////////////
         2eme div  
        ////////////////////////////////////// -->
        <div class="delivery_announcements_details an" id="delivery_announcements_details">
            <h4>Gestion des annonces de livraison</h4>
            <div class="thead theadDiv">
                <div class="deliveryId">Id</div>
                <div class="details_a_delivery">Details de la livraison</div>
                <div class="action">action</div>


            </div>
            <?php
            foreach ($deliveries as $delivery) { ?>
                <div class="managing">
                    <div class="deliveryId id_content"><?= $delivery->getIdDelivery(); ?></div>
                    <div class="details_a_delivery">
                        <div class="delivery_container">
                            <div class="user_details">
                                <div class="user_name">
                                    <div class="user_icon_search">
                                        <i class="fa-solid fa-user"></i>
                                    </div>
                                    <span><?= ucfirst($delivery->getUser()->getFirstname()); ?> </span>
                                </div>
                                <div><span class="delivery_date"><?= $delivery->getSending_date(); ?></span></div>
                                <div class="price_per_kg">
                                    <span><?= $delivery->getPrice(); ?>€/Kg</span>
                                </div>
                            </div>
                            <div class="delivery_details">
                                <div class="depart">
                                    <span><?= $delivery->getDeparture_city(); ?></span>
                                    <span><?= $delivery->getDeparture_time(); ?></span>
                                </div>
                                <div class="line">
                                    <div class="left_line"></div>
                                    <div class="transport">
                                        <?php
                                        $transport = $delivery->getTransport_tool();
                                        if ($transport == 'avion') { ?>
                                            <i class="fa-solid fa-jet-fighter-up fa-rotate-90"></i>
                                        <?php } elseif ($transport == 'bateau') { ?>
                                            <i class="fa-solid fa-ferry"></i>
                                        <?php } elseif ($transport == 'voiture') { ?>
                                            <i class="fa-solid fa-car-side"></i>
                                        <?php } ?>



                                        <p>Max:<?= $delivery->getWeight_limit(); ?>Kg</p>
                                    </div>
                                    <div class="right_line"></div>
                                </div>
                                <div class="dest">
                                    <span><?= $delivery->getDestination_city(); ?></span>
                                    <span><?= $delivery->getArrival_time(); ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="action delete_button_container announcement_delete">

                        <button type="button" class="delivery_delete" name="delivery_delete" data_idDelivery="<?= $delivery->getIdDelivery(); ?>">
                            <i class="fa-solid fa-trash-can" title="Supprimer"></i></button>
                    </div>

                </div><?php } ?>
            <div class="delete_delivery_popup" id="popup">
                <p>Voulez-vous vraiment supprimer cette annonce de livraison?</p>
                <form action="" method="post">
                    <input type="hidden" name="id_delivery" id="id_delivery" value=''>
                    <div class="buttons">
                        <button type="submit" class='delivery_cancel_delete' name="delivery_cancel_delete">Annuler</button>
                        <button type="submit" class='button_delete' name="delivery_delete">Supprimer</button>
                    </div>
                </form>
            </div>

        </div>

        <!-- ////////////////////////////////////////////////
         3eme div  
        ////////////////////////////////////// -->

        <div class="requests_details an" id="requests_details">
            <h4>Gestion des demandes de livraions</h4>
            <div class="thead request_thead">
                <div class="name">Nom de demandeur</div>
                <div class="request_status">Status</div>
                <div class="IdDelivery">Id de la livraison</div>
                <div class="requested_weight">Poids</div>
                <div class="action">Action</div>

            </div>

            <?php
            foreach ($requests as $request) { ?>
                <div class="user_infos">
                    <div class="name">
                        <div class="circle_icon user_connected user_circle_icon">
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <?= ucfirst($request->getUser()->getFirstname()) . ' ' . ucfirst($request->getUser()->getLastname()) ?>
                    </div>
                    <div class="request_status">
                        <?php
                        $request_status = $request->getStatus();
                        if ($request_status == 'Acceptée') { ?>
                            <i class="fa-solid fa-circle" style="color: #3dbf0d;"></i>
                            <span class="font-cirle">Acceptée</span>
                        <?php } else { ?>
                            <i class="fa-solid fa-circle" style="color: #f4ac48;"></i>
                            <span class="font-cirle">En attente</span>


                        <?php } ?>
                    </div>
                    <div class="IdDelivery"><?= $request->getDelivery_Id() ?></div>
                    <div class="requested_weight"><?= $request->getWeight() ?> Kg</div>
                    <div class="action delete_button">
                        <button type="submit" class="request_delete" name="request_delete" data_idRequest="<?= $request->getIdRequest(); ?>">
                            <i class="fa-solid fa-trash-can" title="Supprimer"></i></button>
                    </div>
                </div>
            <?php } ?>
            <div class="delete_request_popup" id="popup">
                <p>Voulez-vous vraiment supprimer cette demande de livraiosn?</p>
                <form action="" method="post">
                    <input type="hidden" name="id_request" id="id_request" value=''>
                    <div class="buttons">
                        <button type="submit" class='request_cancel_delete' name="request_cancel_delete">Annuler</button>
                        <button type="submit" class='button_delete' name="request_delete">Supprimer</button>
                    </div>
                </form>
            </div>

        </div>






    </div>

    </main>


    <script src="<?= asset('js/administration.js'); ?>"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#delete_user_form").on('submit',function(e){
                e.preventDefault();
                let url='administration';
                let data=$(this).serialize();
                $.post(url,data,function(response){
                    $('.delete_user_popup').hide();
                  
                });
            })
        })
    </script> -->