<div class="annonce_details_container">
    <span class="delivery_date"><?= $delivery->getSending_date() ?></span>
    <div class="delivery_container announcement_delivery hover_div">

        <div class="delivery_conten">
            <div class="delivery_details">
                <div class="depart">
                    <span><?= $delivery->getDeparture_city() ?></span>
                    <span><?= $delivery->getDeparture_time() ?></span>
                </div>
                <div class="line">
                    <div class="left_line"></div>
                    <div class="transport">
                        <?php
                        $transport = $delivery->getTransport_tool();
                        if ($transport == 'avion') { ?>
                            <i class="fa-solid fa-jet-fighter-up fa-rotate-90"></i>
                        <?php } elseif ($transport == 'bateau') { ?>
                            <i class="fa-solid fa-ferry"></i>
                        <?php } elseif ($transport == 'voiture') { ?>
                            <i class="fa-solid fa-car-side"></i>
                        <?php } ?>

                    </div>
                    <div class="right_line"></div>
                </div>
                <div class="dest">
                    <span><?= $delivery->getDestination_city() ?></span>
                    <span><?= $delivery->getArrival_time() ?></span>
                </div>
            </div>
        </div>
        <div class="weight_price">
            <div class="max_weight_price left">
                <p class="weight_price_title">Poids maximal</p>
                <p> <?= $delivery->getWeight_limit() ?> Kg</p>
            </div>
            <div class="max_weight_price right">
                <p class="weight_price_title">Prix</p>
                <p> <?= $delivery->getPrice() ?> €/Kg</p>
            </div>
        </div>
        <div class="user_name">
            <div class="user_icon">
                <i class="fa-solid fa-user"></i>
            </div>
            <span><?= $delivery->getUser()->getFirstname() ?></span>
        </div>
        <form id="form" action="" method="post">
            <input type="hidden" name="id_commande" value="1"> <!-- Remplacez "1" par votre propre ID de commande -->
            <input type="submit" id="accepter" name="send" value="Envoyer une demande de livraison ">
        </form>
    </div>
    </main>