<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= asset('css/style.css'); ?>">
    <link rel="stylesheet" href="<?= asset('css/' . $template . '.css'); ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
    <title>ShipMate</title>
</head>

<body>
    <header>
        <nav>
            <div class="nav_container">
                <div class="logo">
                    <a href="./"><img src="<?= asset('images/logo.png'); ?>" alt=""></a>
                </div>
                <div class="nav_links">
                    <div class="links">
                        <a href="./search">
                            <div class="icon search">
                                <i class="fa-solid fa-magnifying-glass nav_icon"></i>
                                <p>Rechercher</p>
                            </div>
                        </a>

                        <a href="./publish">
                            <div class="icon publish">
                                <i class="fa-solid fa-box-open nav_icon"></i>
                                <p>Publier une livraison</p>
                            </div>
                        </a>

                    </div>
                    <?php
                    // Vérifier si l'utilisateur est connecté
                    if (isset($_SESSION['user_logged_in_id'])) {
                        /* var_dump($_SESSION['user_logged_in']); */
                    ?>
                        <button id="user_name">
                            <div class="user icon">
                                <div class="circle_icon user_icon">
                                    <i class="fa-solid fa-user"></i>
                                </div>
                                <span class="logged_name"><?= ucfirst($_SESSION['user_logged_in_name']) ?></span>
                                <i id="chevron" class="fa-solid fa-chevron-down"></i>
                            </div>
                        </button>
                        <div class="menu_container">
                            <a href="./">
                                <i class="fa-solid fa-house"></i>
                                <div class="menu_link">Acceuil</div>
                            </a>
                            <a href="./profile">
                                <i class="fa-solid fa-user"></i>
                                <div class="menu_link">Mon profil</div>
                            </a>
                            <a href="./logout?action=logout">
                                <i class="fa-solid fa-right-from-bracket"></i>
                                <div class="menu_link">Me déconnecter</div>
                            </a>


                        </div>



                    <?php } else { ?>

                        <div class="user icon" id="login_icon">
                            <a id="connexion_link" href="./connexion">
                                <div class="circle_icon user_icon">
                                    <i class="fa-solid fa-user"></i>
                                </div>

                                <div class="seConnecter">Se connecter</div>
                            </a>
                        </div>

                    <?php } ?>

                </div>
            </div>
            </div>
        </nav>
    </header>
    <main>
        <?php include $template . '.phtml'; ?>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script>
            $(document).ready(function() {
                $("#user_name").click(function(e) {
                    e.stopPropagation();
                    $(".menu_container").slideToggle("slow");
                    $("#chevron").toggleClass("rotate");
                });

                $(document).click(function(e) {
                    if (!$(e.target).is("#user_name")) {
                        $(".menu_container").slideUp("slow");
                        $("#chevron").removeClass("rotate");
                    }
                });
            });
        </script>
</body>

</html>