

<div class="form_container">
    <div class=" image form">
        <img src="<?= asset('images/register.PNG'); ?>" alt="">
    </div>
    <div class="login form" id="login" <?php if ($_SESSION['show_signup']) {
                                            echo 'style="display:none"';
                                        } ?>>
        <div class="login_container">
            <h3>Je me connecte</h3>
            <button class="facebook_button" type="button">
                <div class="facebook_login">
                    <i class="fa-brands fa-square-facebook"></i>
                    <p>Se connecter avec Facebook</p>
                </div>

            </button>
            <div class="divider_container">
                <div class="divider"></div>
                <div class="ou">ou</div>
                <div class="divider"></div>
            </div>
            <div class="login_input ">
                <form action="" method="post">
                    <?php if (isset($error_message)) : ?>
                        <p class="error"><?= $error_message; ?></p>
                    <?php endif; ?>
                    <input class="email_input " type="text" placeholder=" Adresse e-mail " name="login_email">
                    <div class="password_container">
                        <input class="password_input" type="password" placeholder=" Mot de passe " name="login_password">
                        <div class="eye"><button class="password_toggle_button"><i class="fas fa-eye-slash"></i></button></div>
                    </div>

                    <a class="forgot_password" href="">Mot de passe oublié ?</a>
                    <button class="log_sign_button" type="submit" name='login_submit'>Se connecter</button>


                    <p>Vous n’avez pas encore de compte ?<a href="" id="login_link"> Inscrivez-vous</a></p>


            </div>
        </div>

    </div>
    <div class="sign_up login form" id="signup" <?php if ($_SESSION['show_signup']) {
                                                    echo 'style="display:flex"';
                                                } ?>>

        <div class="login_container">
            <h3>Je crée un compte </h3>
            <button class="facebook_button" type="button">
                <div class="facebook_login">
                    <i class="fa-brands fa-square-facebook"></i>
                    <p>S'inscrire avec Facebook</p>
                </div>

            </button>
            <div class="divider_container">
                <div class="divider"></div>
                <div class="ou">ou</div>
                <div class="divider"></div>
            </div>
            <button class="mail_button" type="button">
                <div class="facebook_login facebook_singup">
                    <i class="fa-regular fa-envelope"></i>
                    <p>S'inscrire avec une adresse e-mail</p>
                </div>
            </button>
            <div class="signup_input" id="signup_input">
                <p>Saisissez vos informations pour continuer</p>
                <form action="connexion.php" method="post">
                    <input type="text" placeholder=" Votre nom " name="lastname" value="<?= $lastname; ?>">
                    <?php if (isset($errors['lastname'])) : ?>
                        <p class="error"><?= $errors['lastname']; ?></p>
                    <?php endif; ?>
                    <input type="text" placeholder=" Votre prénom " name="firstname" value="<?= $firstname; ?>">
                    <?php if (isset($errors['firstname'])) : ?>
                        <p class="error"><?= $errors['firstname']; ?></p>
                    <?php endif; ?>
                    <input type="text" placeholder=" Votre numéro de téléphone " name="phone_number" value="<?= $phone_number; ?>">
                    <?php if (isset($errors['phone_number'])) : ?>
                        <p class="error"><?= $errors['phone_number']; ?></p>
                    <?php endif; ?>
                    <input type="email" placeholder=" Votre adresse e-mail " name="email" value="<?= $email; ?>">
                    <?php if (isset($errors['email'])) : ?>
                        <p class="error"><?= $errors['email']; ?></p>
                    <?php endif; ?>
                    <div class="signup_password">
                        <input type="password" class="password_input" placeholder=" Votre mot de passe " name="password">
                        <div class="eye"><button class="password_toggle_button"><i class="fas fa-eye-slash"></i></button></div>
                    </div>
                    <?php if (isset($errors['password'])) : ?>
                        <p class="error"><?= $errors['password']; ?></p>
                    <?php endif; ?>
                    <button class="log_sign_button sign" type="submit" name='signup_submit'>Se connecter</button>
                </form>
                <p>Vous avez déjà un compte ?<a href="" id="signup_link"> Connectez-vous</a></p>

            </div>

        </div>

    </div>

</div>
</main>

<script src="<?= asset('js/connexion.js'); ?>"></script>