   <div class="profile_container">
       <h3>Bienvenue Nour,</h3>
       <div class="profile_details_container">
           <div class="titles">
               <div class="informations">
                   <p>Informations personelles</p>
               </div>
               <div class="announcement">
                   <p>Annonces</p>
               </div>
               <div class="request">
                   <p>Livraisons</p>
               </div>
           </div>

           <!-- /////////////////////////////////////////////////////////////////////
           le section dES INFORMATIONS PERSONNELLES
           /////////////////////////////////////////////////////////////////// -->
           <div class="informations_details">
               <form action="" method="post">
                   <div class="firstname">
                       <label for="firstname">Prénom</label>
                       <input type="text" id='firstname' name='newFirstname' value="<?= isset($_POST['newFirstname']) ? $_POST['newFirstname'] : $currentUser->getFirstname() ?>">
                   </div>
                   <?php if (isset($errors['newFirstname'])) : ?>
                       <p class="error informations_form"><?= $errors['newFirstname']; ?></p>
                   <?php endif; ?>
                   <div class="lastname ">
                       <label for="lastname">Nom</label>
                       <input type="text" id='lastname' name='newLastname' value="<?= isset($_POST['newLastname']) ? $_POST['newLastname'] : $currentUser->getLastname() ?>">
                   </div>
                   <?php if (isset($errors['newLastname'])) : ?>
                       <p class="error informations_form"><?= $errors['newLastname']; ?></p>
                   <?php endif; ?>
                   <div class="number_phone">
                       <label for="number_phone">Numéro de téléphone</label>
                       <input type="text" id='number_phone' name='newPhone_number' value=" <?= isset($_POST['newPhone_number']) ? $_POST['newPhone_number'] : $currentUser->getPhone_number(); ?>">
                   </div>
                   <?php if (isset($errors['newPhone_number'])) : ?>
                       <p class="error informations_form"><?= $errors['newPhone_number']; ?></p>
                   <?php endif; ?>
                   <div class="email">
                       <label for="email">Adresse e-mail</label>
                       <input type="email" id='email' name='newEmail' value="<?= isset($_POST['newEmail']) ? $_POST['newEmail'] : $currentUser->getEmail(); ?>">
                   </div>
                   <?php if (isset($errors['newEmail'])) : ?>
                       <p class="error informations_form"><?= $errors['newEmail']; ?></p>
                   <?php endif; ?>
                   <div class="password">
                       <label for="password">Mot de passe</label>
                       <input type="password" id='password' name='currentPassword' value="<?= isset($_POST['currentPassword']) ? $_POST['currentPassword'] : ""; ?>">
                   </div>
                   <?php if (isset($errors['currentPassword'])) : ?>
                       <p class="error informations_form"><?= $errors['currentPassword']; ?></p>
                   <?php endif; ?>

                   <div class="password">
                       <label for="new_password">Nouveau mot de passe</label>
                       <input type="password" id='newPassword' name='newPassword'>

                   </div>
                   <?php if (isset($errors['newPassword'])) : ?>
                       <p class="error informations_form"><?= $errors['newPassword']; ?></p>
                   <?php endif; ?>
                   <button class="modify_button" type="submit" name='modify_submit'>Modifier mes informations</button>
               </form>

               <?php
                if (isset($_SESSION['message_flash'])) {
                    // Affichez le message flash
                ?>
                   <div class="message_flash">
                       <p><?= $_SESSION['message_flash'];
                            unset($_SESSION['message_flash']); ?></p>
                   </div>
               <?php
                }

                ?>

           </div>


           <!-- /////////////////////////////////////////////////////////////////////
                       le section des annonces
                /////////////////////////////////////////////////////////////////// -->

           <div class="announcement_details">
               <h4>Mes annonces</h4>
               <?php
                if (count($deliveries) == 0) { ?>
                   <div class="no_result">
                       <h3>Vous n'avez aucune annonce</h3>
                   </div>
               <?php } else { ?>
                   <div class="search_results">

                       <?php foreach ($deliveries as $delivery) { ?>

                           <div class="delivery_container announcement_delivery hover_div">
                               <div class="delivery_conten">

                                   <div class="user_details">
                                       <div class="user_name">
                                           <span class="delivery_date"><?= $delivery->getSending_date(); ?></span>
                                       </div>
                                       <div class="price_per_kg">
                                           <span><?= $delivery->getPrice(); ?> €/Kg</span>
                                       </div>
                                   </div>
                                   <div class="delivery_details">
                                       <div class="depart">
                                           <span><?= $delivery->getDeparture_city(); ?></span>
                                           <span><?= $delivery->getDeparture_time(); ?></span>
                                       </div>
                                       <div class="line">
                                           <div class="left_line"></div>
                                           <div class="transport">
                                               <?php
                                                $transport_tool = $delivery->getTransport_tool();
                                                if ($transport_tool == 'avion') { ?>
                                                   <i class="fa-solid fa-jet-fighter-up fa-rotate-90"></i>
                                               <?php } elseif ($transport_tool == 'bateau') { ?>
                                                   <i class="fa-solid fa-ferry"></i>
                                               <?php } elseif ($transport_tool == 'voiture') { ?>
                                                   <i class="fa-solid fa-car-side"></i>
                                               <?php } ?>



                                               <p>Max: <?= $delivery->getWeight_limit(); ?> Kg</p>
                                           </div>
                                           <div class="right_line"></div>
                                       </div>
                                       <div class="dest">
                                           <span><?= $delivery->getDestination_city(); ?></span>
                                           <span><?= $delivery->getArrival_time(); ?></span>
                                       </div>
                                   </div>
                               </div>
                               <div class="requests_container delivery_requests">
                                   <?php
                                    $delivery_requests = $RequestModel->getRequests($delivery->getIdDelivery());
                                    //  echo '<pre>';
                                    //  print_r($delivery_requests);
                                    //  $requesttts=[];
                                    if (count($delivery_requests) == 0) { ?>
                                       <div class="no_result">
                                           <h3>Aucune demande pour cette annonce</h3>
                                       </div>
                                   <?php } else { ?>
                                       <div class="requests_list">
                                           <div class="titles_list">
                                               <div class="name_list">
                                                   <p>Prénom</p>
                                               </div>
                                               <div class="weight_list">
                                                   <p>Poids</p>
                                               </div>
                                               <div class="status_list">
                                                   <p>Status</p>
                                               </div>
                                           </div>

                                           <?php
                                            $statuus = 'NON ACCEPTE';
                                            foreach ($delivery_requests as $delivery_request) { ?>
                                               <div class="request_details">

                                                   <div class="request_user">
                                                       <div class="user_name">
                                                           <div class="user_icon_profile">
                                                               <i class="fa-solid fa-user"></i>
                                                           </div>
                                                           <span><?= ucfirst($delivery_request->getUser()->getFirstname()); ?></span>
                                                       </div>
                                                   </div>
                                                   <div class="request_user">
                                                       <span><?= $delivery_request->getWeight(); ?> Kg</span>
                                                   </div>
                                                   <div class="request_user statuss" id="statuss">
                                                       <?php
                                                        $status_requests = $delivery_request->getStatus();
                                                        if ($status_requests == 'Acceptée') { ?>
                                                           <i class="fa-regular fa-circle-check" style="color: #17a139;"></i>
                                                       <?php } else { ?>

                                                           <form id="form" action="" method="post">
                                                               <input type="hidden" name="id_commande" value="1"> <!-- Remplacez "1" par votre propre ID de commande -->
                                                               <input type="submit" id="accepter" name="accept" value="Accepter">
                                                           </form>
                                                       <?php } ?>

                                                   </div>

                                               </div>
                                           <?php } ?>
                                       </div>
                                   <?php } ?>
                               </div>
                           </div>
                       <?php   } ?>
                   </div>
               <?php  }
                ?>
           </div>



           <div class="request_details_container">
               <h4>Mes livraisons</h4>
               <?php
                if (count($requests) == 0) { ?>
                   <div class="no_result">
                       <h3>Vous n'avez aucune livraison</h3>
                   </div>
               <?php } else { ?>
                   <div class="search_results">

                       <?php foreach ($requests as $request) { ?>

                           <div class="delivery_container">
                               <div class="delivery_conten">

                                   <div class="user_details">
                                       <div class="user_name">
                                           <div class="user_icon_profile">
                                               <i class="fa-solid fa-user"></i>
                                           </div>
                                           <span>
                                               <?= ucfirst($request->getDelivery()->getUser()->getFirstname()); ?>
                                           </span>

                                       </div>
                                       <div class="delivery_date">
                                           <span class="delivery_date"><?= $request->getDelivery()->getSending_date(); ?></span>
                                       </div>
                                       <div class="price_per_kg">
                                           <span><?= $request->getDelivery()->getPrice(); ?> €/Kg</span>
                                       </div>
                                   </div>
                                   <div class="delivery_details">
                                       <div class="depart">
                                           <span><?= $request->getDelivery()->getDeparture_city(); ?></span>
                                           <span><?= $request->getDelivery()->getDeparture_time(); ?></span>
                                       </div>
                                       <div class="line">
                                           <div class="left_line"></div>
                                           <div class="transport">
                                               <?php
                                                $tool = $request->getDelivery()->getTransport_tool();
                                                if ($tool == 'avion') { ?>
                                                   <i class="fa-solid fa-jet-fighter-up fa-rotate-90"></i>
                                               <?php } elseif ($tool == 'bateau') { ?>
                                                   <i class="fa-solid fa-ferry"></i>
                                               <?php } elseif ($tool == 'voiture') { ?>
                                                   <i class="fa-solid fa-car-side"></i>
                                               <?php } ?>



                                               <p>Poids: <?= $request->getWeight(); ?> Kg</p>
                                           </div>
                                           <div class="right_line"></div>
                                       </div>
                                       <div class="dest">
                                           <span><?= $request->getDelivery()->getDestination_city(); ?></span>
                                           <span><?= $request->getDelivery()->getArrival_time(); ?></span>
                                       </div>
                                   </div>
                               </div>
                               <div class="devider"></div>
                               <div class="user_contact">
                                   <i class="fa-regular fa-comments"></i><p>Contacter <?= ucfirst($request->getDelivery()->getUser()->getFirstname()); ?></p>
                               </div>
                               <div class="devider bottom"></div>
                               <div class="requests_container st">
                                   <?php
                                    $status = $request->getStatus();
                                    if ($status == 'Acceptée') { ?>
                                       <i class="fa-solid fa-circle" style="color: #3dbf0d;"></i>
                                       <span class="font-cirle">Acceptée</span>
                                   <?php } else { ?>
                                       <i class="fa-solid fa-circle" style="color: #f4ac48;"></i>
                                       <span class="font-cirle">En attente</span>


                                   <?php } ?>
                               </div>
                           </div>
                       <?php   } ?>
                   </div>
               <?php  }
                ?>
           </div>
       </div>
   </div>
   </main>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
   <script src="<?= asset('js/delivery.js'); ?>"></script>
   <script>
       $(document).ready(function() {
           $(".announcement_delivery").click(function() {
               // The .index() function retrieves the index of the currently clicked element, relative to the elements with the ".delivery_container" class.
               var index = $(".announcement_delivery").index(this);
               // The .siblings() function selects all elements that share the same parent as the clicked element, but are not the clicked element itself. We then add the .find() function to select the associated ".price_sending_request" elements. Finally, we use the .slideUp() function to hide these elements.
               $(this).siblings(".announcement_delivery").find(".delivery_requests").slideUp();
               // The .find() function is used to select the ".price_sending_request" element associated with the clicked element. We then use the .slideToggle() function to show or hide this element.

               $(this).find(".delivery_requests").slideToggle("slow");
           });
       });
   </script>