<div class="search_container">
    <h3>Trouver votre livreur </h3>
    <?php if (isset($msg_error)) : ?>
        <p class="error"><?= $msg_error; ?></p>
    <?php endif; ?>
    <div class="search_form" <?php if (isset($msg_error)) {
                                    echo 'style="border: 2px solid red"';
                                } ?>>
        <form action="" method="POST">
            <div class="input_container city_input_container">
                <label for="departure">
                    <i class="fa-regular fa-circle-dot"></i>
                </label>
                <input type="text" class='city_input' id="departure" name='departure' placeholder="Départ" <?php if (isset($departure)) { ?> value="<?= $departure;
                                                                                                                                                } ?>">

                <!-- div qui contient le résultat de recherche -->
                <div class="list_container">
                    <ul class="cities_list"></ul>
                </div>

            </div>
            <div class="input_container city_input_container">
                <label for="destination">
                    <i class="fa-regular fa-circle-dot"></i>
                </label>
                <input type="" class='city_input' id="destination" name='destination' placeholder="Destination" <?php if (isset($destination)) { ?> value="<?= $destination;
                                                                                                                                                        } ?>">

                <!-- div qui contient le résultat de recherche -->
                <div class="list_container">
                    <ul class="cities_list"></ul>
                </div>
            </div>
            <div class="input_container date_weight">
                <div class="date_input_container">
                    <label for="date">
                        <i class="fa-regular fa-calendar"></i>
                    </label>
                    <input class="date_input" type="date" id="date" name="date" placeholder="Date d'envoi " <?php if (isset($date)) { ?> value="<?= $date;
                                                                                                                                            } ?>">

                </div>
                <div class="weight_input">
                    <label for="weight">
                        <i class="fa-solid fa-weight-scale"></i>
                    </label>
                    <input type="number" id="weight" name="weight" placeholder="Poids " min="1" step="1" <?php if (isset($weight)) { ?> value="<?= $weight;
                                                                                                                                            } ?>">

                    <span>Kg</span>
                </div>
            </div>
            <div class="input_container_button">
                <button id="search_button" type="submit" name="search">Rechercher</button>
            </div>
        </form>
    </div>
    <div class="result_container">

        <?php
        if (isset($_POST['search'])) {
            if (isset($results)) {
                if (count($results) == 0) { ?>
                    <div class="no_result">
                        <h3> Aucun résultat trouvé</h3>
                    </div>
                <?php } else { ?>
                    <div class="search_results">
                        <span class="delivery_date"><?= date('d-m-Y', strtotime($_POST['date'])); ?></span>
                        <?php foreach ($results as $result) { ?>

                            <!-- <a href="<= constructUrl('annonce_details', ['id' => $result->getIdDelivery()]); ?>"> -->
                            <div class="delivery_container">
                                <div class="user_details">
                                    <div class="user_name">
                                        <div class="user_icon_search">
                                            <i class="fa-solid fa-user"></i>
                                        </div>
                                        <span><?= ucfirst($result->getUser()->getFirstName()) ?></span>
                                    </div>
                                    <div class="price_per_kg">
                                        <span><?= $result->getPrice() ?> €/Kg</span>
                                    </div>
                                </div>
                                <div class="delivery_details">
                                    <div class="depart">
                                        <span><?= $result->getDeparture_city() ?></span>
                                        <span><?= $result->getDeparture_time() ?></span>
                                    </div>
                                    <div class="line">
                                        <div class="left_line"></div>
                                        <div class="transport">
                                            <?php
                                            $transport = $result->getTransport_tool();
                                            if ($transport == 'avion') { ?>
                                                <i class="fa-solid fa-jet-fighter-up fa-rotate-90"></i>
                                            <?php } elseif ($transport == 'bateau') { ?>
                                                <i class="fa-solid fa-ferry"></i>
                                            <?php } elseif ($transport == 'voiture') { ?>
                                                <i class="fa-solid fa-car-side"></i>
                                            <?php } ?>



                                            <p>Max: <?= $result->getRemaining_Weight() ?> Kg</p>
                                        </div>
                                        <div class="right_line"></div>
                                    </div>
                                    <div class="dest">
                                        <span><?= $result->getDestination_city() ?></span>
                                        <span><?= $result->getArrival_time() ?></span>
                                    </div>
                                </div>

                                <div class="price_sending_request">
                                    <div class="devider"></div>
                                    <div class="total_price">
                                        <p class="">Prix total pour <?= $weight; ?> Kg </p>
                                        <?php $totale_price = $result->getPrice() * $weight; ?>
                                        <p id="total_price"> <?= $totale_price; ?> €</p>
                                    </div>
                                    <div class="devider bottom"></div>

                                    <?php
                                    $already_requested = false;
                                    if (isset($_SESSION['user_logged_in_id'])) {
                                        foreach ($requests as $request) {
                                            if ($result->getIdDelivery() == $request->getDelivery_id()) {;
                                                $already_requested = true;
                                                break;
                                            }
                                        }
                                        if ($_SESSION['user_logged_in_id'] == $result->getUser()->getIdUser()) {
                                        } elseif ($already_requested) {
                                    ?>
                                            <div class="user_contact">
                                                <i class="fa-regular fa-comments"></i>
                                                <p>Contacter <?= ucfirst($result->getUser()->getFirstName()) ?></p>
                                            </div>
                                            <div class="devider bottom"></div>
                                            <div class="already_requested">
                                                Demande déjà envoyée
                                            </div>
                                        <?php } else { ?>
                                            <div class="user_contact">
                                                <i class="fa-regular fa-comments"></i>
                                                <p>Contacter <?= $result->getUser()->getFirstName() ?></p>
                                            </div>
                                            <div class="devider bottom"></div>

                                            <div class="sending_request">
                                                <form id="form" action="" method="post">
                                                    <input type="hidden" name="id_delivery" value="<?= $result->getIdDelivery() ?>">
                                                    <input type="hidden" name="user_weight" value="<?= $weight; ?>">
                                                    <input type="submit" id="send" name="send" value="Envoyer une demande de livraison ">
                                                </form>
                                            </div>
                                    <?php }
                                    }else{?>
                                        <div class="user_contact">
                                        <i class="fa-regular fa-comments"></i>
                                        <p>Contacter <?= $result->getUser()->getFirstName() ?></p>
                                    </div>
                                    <div class="devider bottom"></div>

                                    <div class="sending_request">
                                        <form id="form" action="" method="post">
                                            <input type="hidden" name="id_delivery" value="<?= $result->getIdDelivery() ?>">
                                            <input type="hidden" name="user_weight" value="<?= $weight; ?>">
                                            <input type="submit" id="send" name="send" value="Envoyer une demande de livraison ">
                                        </form>
                                    </div> <?php }?>

                                </div>



                            </div>




                        <?php   } ?>
                    </div>
        <?php  }
            }
        }
        ?>




    </div>






</div>
</main>

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/flatpickr.min.js"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/fr.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
    flatpickr("#date", {
        // Initialiser Flatpickr avec la langue française
        "locale": "fr",
        minDate: "today",
        altInput: true,
        altFormat: " j F Y",

    });

    $(document).ready(function() {
        $(".delivery_container").click(function() {
            // The .index() function retrieves the index of the currently clicked element, relative to the elements with the ".delivery_container" class.
            var index = $(".delivery_container").index(this);
            // The .siblings() function selects all elements that share the same parent as the clicked element, but are not the clicked element itself. We then add the .find() function to select the associated ".price_sending_request" elements. Finally, we use the .slideUp() function to hide these elements.
            $(this).siblings(".delivery_container").find(".price_sending_request").slideUp();
            // The .find() function is used to select the ".price_sending_request" element associated with the clicked element. We then use the .slideToggle() function to show or hide this element.

            $(this).find(".price_sending_request").slideToggle("slow");
        });
    });
</script>
<script src="<?= asset('js/geonamesApiAjax.js'); ?>"></script>