<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="<?= asset('css/success.css'); ?>">
</head>
<body>
    <div class="success_container">
        <img src="<?= asset('images/tick.webp'); ?>" alt="">
        <div class="success_message">
            <p class="title">Votre demande a été bien envoyée au livreur</p>
            <p class="para">  Votre demande a été transmise efficacement au livreur. Nous sommes désormais en attente de la réponse du livreur pour pouvoir vous la communiquer via votre profil.  </p>
            <a href="./"><button> <i class="fa-solid fa-chevron-left"></i> Retour à la page d'acceuil</button></a>
        </div>
    </div>
</body>
</html>